apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:14asDWc=,iv:Ze+wxE7SVvSF6ND9LjJHqPsXZNNp+6n0J9MQ5IZFWf8=,tag:ntvYKikPuztdew7y9Sl7gw==,type:str]
    admin-password: ENC[AES256_GCM,data:GsrI/amjTdI=,iv:26zmEqx4AErcU6VYhMhU0KomWOVDV5Oy10I297bfWzU=,tag:M4lpGYbCJa603Pb9VvIieA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2YXJ2ZTNtVTl0VkIzYmVa
            YW5lMmZPMTVzMlFUWmQ2TVdZcDI3QklzVzE4CjBtYW4xczlzcEd3MDBxVFN0ZS9Y
            a1ltV0tEMW9xRFhTN3ZyTUZoMG1PT1EKLS0tIG1BK0FpUHQ4QXd2dUVKQUptV1dC
            QWQwZzNDMUE0a1NQZzlxTEhhNGZmc2MKZcb/ZWgA7AsjoutKTXJlphxIxYJtKW7H
            FU+5lHbh4S6V5O9LLPLJu7+8pANhGBr3uf5vAsz13y+sXk6R4Fdmsg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mskvtzf73xl8nxh5lt6ea3llxzmdar7sctsxwz3ymjnv8sw3ev5s99r353
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-22T06:08:41Z"
    mac: ENC[AES256_GCM,data:TTcOZNtTTI4j32Fwa7BobbK/XeMwE13xmbLrP+J0+W1cWhCPtYk3TFlPmKWwI3QbW3DgTEL+jrLRgvWOx8F/b9L0Rw6HHPtaIuh3pWCSxbEXq97znOjkeyUFVligSx1RAqDv8qSKfslxkEKRplvTKCfIFt8HBuM40ri0bGMPvjA=,iv:GR+eMInNHT/9SRuRbwirNDThCmvW4wz0+TgcGF+PQNc=,tag:rC53AgyOJ0Zj7exG5QGXiw==,type:str]
    version: 3.13.3
