apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: monitoring
type: Opaque
stringData:
    admin-password: ENC[AES256_GCM,data:wkKJ0gPoUSk=,iv:J6os5+f0PSqWTiBexVVBosDBh6RU5gLWonT8ZyV7IS8=,tag:65U05ugCo3GqTReWOAfq5Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGQTRlWmJaSnpZdG10akZz
            TnRKN1FTNitmRGdmK0x0MUJxWTF6VUJvM0ZvCmVPeVF0RW04QWkxTHdWT0U1dUZF
            OHRQQ2ovRXJTUGpWckFGVnhERjdCKzQKLS0tIFMyN2ZCVEdZV3VpdFpWVTJRSDhy
            OW0vYkpwR2hwczBhb1RreVNKMEpnTlkKYiWrPStBWTIha7fP5BPmhKrGxdQYxZEo
            4N6hw81xgBwRpyFM9X7gI/XLXJ4s4XgywGaWQ37sOsIEjXuup5Xc3A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mskvtzf73xl8nxh5lt6ea3llxzmdar7sctsxwz3ymjnv8sw3ev5s99r353
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-22T05:33:48Z"
    mac: ENC[AES256_GCM,data:wknR1pXcl5Wx3QdBqSMBgVCO5TojJlCXyaFy2IXi/NA4YGd7ikmm+zhd65mPh4jUFMfg4ncjfpzEz2vDgXpnJUQus8CaJoA/GghFCWhCC+YwsuTIG9Y7UkJRl0DZlT8Tp+K8gqmvPZv5xHOSbqVaZflyshai2APETJ57zNnb6tQ=,iv:rZyDb2v+JNdpqtR9NUhJr9QqJjsAaTQCyAG0R+q+qcY=,tag:znCTRH+hdehiU12StpfDIA==,type:str]
    version: 3.13.3
