---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: downloads
spec:
  interval: 1h
  chart:
    spec:
      chart: app-template
      # TODO: check https://bjw-s-labs.github.io/helm-charts for the latest.
      version: "3.7.3"
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      qbittorrent:
        containers:
          main:
            image:
              repository: ghcr.io/home-operations/qbittorrent
              tag: 5.0.3
            env:
              UMASK: "022"
              QBT_WEBUI_PORT: "8080"
            resources:
              requests:
                cpu: 25m
                memory: 128Mi
    service:
      main:
        controller: qbittorrent
        ports:
          http:
            port: 8080
    ingress:
      main:
        enabled: true
        className: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-staging
        hosts:
          - host: qbittorrent.example.com # TODO: your domain
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
                  port: http
        tls:
          - secretName: qbittorrent-tls
            hosts:
              - qbittorrent.example.com # TODO: your domain
    persistence:
      config:
        existingClaim: qbittorrent-config
        globalMounts:
          - path: /config
      downloads:
        existingClaim: qbittorrent-downloads
        globalMounts:
          - path: /downloads
