---
apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system
  labels:
    # MetalLB needs privileged pod security to run its speaker.
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
