# !!! ENCRYPT THIS FILE BEFORE COMMITTING !!!
#   sops --encrypt --in-place apps/base/minecraft/secret.sops.yaml
apiVersion: v1
kind: Secret
metadata:
    name: minecraft-rcon
    namespace: minecraft
type: Opaque
stringData:
    #ENC[AES256_GCM,data:PyrDh3U9QDgeLDxELxFEPxleCjpLNCtW9ALWb1m+FI55bmc/3ESc/bDUQQc8+2ncYrhDm9ch5OVbuRBRG+3TW0n6wcBW,iv:zlUx6nMUyjebSGmng7+GVnCqxG/cC4mrCM3si8a7rx0=,tag:ae1wSBIXT4ofzhKoGIjQew==,type:comment]
    rcon-password: ENC[AES256_GCM,data:3TdW6+wUZzU=,iv:c7BzgjVr7f8Js/hDBm9Gz4WAFB4rtrx4YKz7FKBnflg=,tag:bqW6UiilfBVts3T+EiMqPA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZOGhIb3FwZHZpenhudmx4
            b3FXSHRXUXJ0R0hZRkhMVCtQenFoTjlTbkNZClVNNEJXc3BsQWxCdlk1eHlyT1g3
            RE1GYU4yQVB1dy9QNTR0Q1lndFZPMFUKLS0tIE05dWZMR1p6cjBLQk5LWTZPYnB0
            MmphbXdiTThvakFyZ1JlTlQ5YmluUU0KB1NsqrzK/o+d17l7eJLGwAuCa3LHrbTR
            SbS8g8AkA5DKHUoNotid6hWs13wTi/7Mzfvyg8BgO5R6nuGDwLoCBQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mskvtzf73xl8nxh5lt6ea3llxzmdar7sctsxwz3ymjnv8sw3ev5s99r353
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-22T12:01:05Z"
    mac: ENC[AES256_GCM,data:6auIDnJA0Ki1g+Vro2pnxOHt+Dp1HscTDx7eVfNpNDFTq4RwqtJQp7GRyzufsp0Nv3+Y0avK9CEFeFEEg71OWuqmtRCwU742Ztr6sswLjCxns2y2hDUSZ9cEd0dABNaXYgaCJiS9dmHyuzyx/FUw6efELjBemc1CVgxYfd4FlPw=,iv:IV37zH1bvk3s2mr436MZ9QOViBGaENm5dye4CaFc04s=,tag:gHtoUxfnvALaRVQnhlM8fQ==,type:str]
    version: 3.13.3
