# !!! ENCRYPT THIS FILE BEFORE COMMITTING !!!
#   sops --encrypt --in-place apps/base/immich/secret.sops.yaml
#
# Password for the `immich` Postgres role. Used by BOTH the Postgres StatefulSet
# (POSTGRES_PASSWORD) and the Immich server (DB_PASSWORD).
apiVersion: v1
kind: Secret
metadata:
    name: immich-db
    namespace: immich
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:L+bkm2xfYXsQZj5aaAnVEjp49yIIB/yEeT+JMiu1Pg==,iv:J1Ndda+JCpE5Ax7Is1LDvlzVUB38vpCszoH2yea8l68=,tag:vy9Eg9unSq8XC9s+B51CRw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArOG5ScjAwL0pKQmdCVktu
            Y0dWaWdqNndvTWZsQWVKS2ZlQlFMclNwZXhvCkpnODFNNTR0OGZpdlhIdmgwbFkz
            WUNuUkxuSGJ0eG1MMklHZjE1RVBobXMKLS0tIHFKR0FoMVFSQW01Qjgxek9wN0FP
            cC9HajhGb1k1b0JkZGRqckZqYlhEcHMKSSTpfqzy/sMtl8r4UO8B+ePEBYUrOCbD
            S6kv6Tf2F3d26CsTrWKSL+Krvnb32SFOzP4dtQKX9519ZlAHsHvFLw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mskvtzf73xl8nxh5lt6ea3llxzmdar7sctsxwz3ymjnv8sw3ev5s99r353
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-31T07:50:39Z"
    mac: ENC[AES256_GCM,data:Mikn4f3Z7aRfj9FvwX4bRbXNcj/UOGaCKYuwSKcxksOvIJlkQqj7Wsuu9pzHhvIajvryFr2BmCvy/oJWnyzcka93PG7sLnanwt3Nl23iij4DjQn4PlpgAfllRWyqb4QG14dsKoqOz2n+84nZUBGheq0KEIL2DKf3Y/zqxMd1yL8=,iv:OT5oYkaEukx4QmcxHGDcqs2+SV7MpX42gO5Pvora3uQ=,tag:j5IgNIA4svGbG5fARfKk3A==,type:str]
    version: 3.13.3
